# This is the Cakefile for this project.
# Feel free to add Cakefiles to your own projects!

[metadata]
name = "yeah"
description = "Cakecutter ttemplate (For rust)"

# Questions
[[questions.a]]
type = "input"
ques = "What the heck is your name?"
default = "John Doe"

[[questions.ts]]
type = "menu"
ques = "What is your favorite color?"
options = [
    "Yes", "No"
]

[filestructure]
"tsconfig.json" = """
{{if eq (index . "ts") "Yes"}}
    true
{{else}}
    false
{{end}}
"""
"src/" = "true"

# If you want to, you can literally write all the content here in one file but then what's the point of a "template" lol
[content]
"tsconfig.json" = """
{{index . "a"}}
"""


[commands]
"npm -y init" = """
{{if eq (index . "ts") "Yes"}}
    true
{{else}}
    false
{{end}}
"""
