# This is the Cakefile for this project.
# Feel free to add Cakefiles to your own projects!

[metadata]
name = "cc"
description = "Cakecutter template example" # You need to write metadata for every cake

# Questions
[[questions.a]]
type = "input" # This can be input | menu | select
ques = "What is your name?"
default = "John Doe"

[[questions.ts]]
type = "menu"
ques = "What is your favorite color?"
options = [
    "Yes", "No"
]

[filestructure]
"tsconfig.json" = """
{{if eq (index . "ts") "Yes"}}
    true
{{else}}
    false
{{end}}
""" 
# Cakecutter uses go's template syntax.
# In the above example, if ts is "Yes", then the file will be created.

"src/" = "true"

# If you want to, you can literally write all the content here in one file but then what's the point of a "template" lol
[content] # Write template content here, things like 
"tsconfig.json" = """
{{index . "a"}}
"""


[commands]
"npm -y init" = """
{{if eq (index . "ts") "Yes"}}
    true
{{else}}
    false
{{end}}
"""

# You can find more examples in the /examples folder.